### PR TITLE
Add rules for older json-based CODEX and RNAseq

### PR DESCRIPTION
**Pull request by jswelling**
This PR replaces the rule chain in src/routes/assayclassifier with the most recent version from soft-assay-rules:main .  This update provides special rules which provide vitessce hints needed by the Portal for certain very old RNAseq and CODEX derived datasets with internal structure based on json files. Other recent detailed updates from the main branch of soft_assay_rules are also included.

### CODE REVIEW

**Review by jpuerto-psc — CHANGES_REQUESTED** [review]
@jswelling I think that the main branch on soft-assay-types was out of sync with the latest changes on ingest-api. Are we trying to bring in the dag_provenance_list changes? If so, can we bring just those in and put the PR against the `dev-integrate` branch?

**Comment by yuanzhou** [comment]
@jswelling @jpuerto-psc I changed the base branch to `dev-integrate` to follow the workflow. Please coordinate and sort out the rule chain updates since we have recent updates @jpuerto-psc made in the following PRs: #476 #478 (already verified on TEST) and the new one #480

**Review by jpuerto-psc — APPROVED** [review]

**Comment by yuanzhou** [comment]
@jswelling I hate to say this, you'll have to back put the last commit `2e2eb7f8a59527a4c845da33cf7e31f22d7e07e5` because our workflow is NEVER merge `dev-integrate` into a bug fix or feature branch. You'll always pull the latest `main` into your branch. And if there's any merge conflicts in this PR, I'll resolve when I merge or reach out to ask your help when I don't understand how to fix the conflicts.

**Comment by jswelling** [comment]
@yuanzhou I don't understand the question.  dev-integrate was never merged into the branch from which this PR was created.

**Comment by jswelling** [comment]
Gaah- @yuanzhou I see it in the network but I don't remember going it.  If I remove it, I'll include deltas in this PR for files outside the single file I'm trying to update.  I'll revert that commit, but I think it will increase the number of conflicts that have to be resolved, not decrease them.  @jpuerto-psc because of this workflow issue it may be necessary to completely abandon this PR, wait until all your earlier changes have settled in main, and then create a new PR from that future version of main with the exact same changes as exist in this PR.

**Comment by jswelling** [comment]
@yuanzhou No, my branch was created from main back in late Jan.  The confusion in the mean time is because @jpuerto-psc had mods that were still in dev-integrate at that time, and without the correction from dev-integrate I was accidentally generating anti-changes in my PR. So I acknowledge that I have to start from scratch, but I did start from main in the first place.
image

**Comment by jswelling** [comment]
Replaced by #493

**Pull request closed without merging**
