### PR TITLE
Jpuerto/assay classifier updates

### PR DESCRIPTION
**Pull request by yuanzhou**
Following merged PR #454 #456 #458 #460 for TEST

### CODE REVIEW

**Comment by tjmadonna** [comment]
@jpuerto-psc @yuanzhou I see that this line is setting `metadata` to a dictionary after setting `metadata` in conditional statements. Is this correct? It seems like those conditionals aren't doing anything.

https://github.com/hubmapconsortium/ingest-api/blob/b9d9b3246f62ce4206bca6fb5b93f26bc23f9216/src/routes/assayclassifier/__init__.py#L100

**Comment by jpuerto-psc** [comment]
> @jpuerto-psc @yuanzhou I see that this line is setting `metadata` to a dictionary after setting `metadata` in conditional statements. Is this correct? It seems like those conditionals aren't doing anything.
> 
> https://github.com/hubmapconsortium/ingest-api/blob/b9d9b3246f62ce4206bca6fb5b93f26bc23f9216/src/routes/assayclassifier/__init__.py#L100

This is out of date - was resolved in newer commits

**Comment by yuanzhou** [comment]
@jpuerto-psc this draft PR will be replaced by #464 since Joel's branch has all your commits. If no objection, we'll close this PR and use `welling/cleanup_and_add_provenance` moving forward for TEST.

**Comment by jpuerto-psc** [comment]
@yuanzhou - I'd like to keep these things separate. I believe that this PR is actually ready for merging and since Joel is only in twice a week, his PR may take a bit longer to incorporate/test.

**Pull request merged**
