### PR TITLE
Welling/soft assay types start

### PR DESCRIPTION
**Pull request by jpuerto-psc**
Updates to rules classifier

### CODE REVIEW

**Comment by yuanzhou** [comment]
@jpuerto-psc @gesinaphillips to be clear, when I merge this PR and redeploy the updated `dev-integrate` branch on DEV, I'll be building the ingest-api by pulling the latest commit from IVT `phillips/multi-assay` branch?

**Comment by jpuerto-psc** [comment]
@yuanzhou - that is right. Please wait for @jswelling to confirm that this is ready to merge, seems like there are a few merge conflicts that need to be resolved.

**Comment by jpuerto-psc** [comment]
@yuanzhou - should be good to merge here!

**Comment by yuanzhou** [comment]
@gesinaphillips I'm afraid that you'll have to back out the commit https://github.com/hubmapconsortium/ingest-api/pull/435/commits/82df881404e55e3367ad841dc796d997d34f5e9e, our workflow is NEVER merge `dev-integrate` into your feature branch.

**Comment by gesinaphillips** [comment]
> @gesinaphillips I'm afraid that you'll have to back out the commit [82df881](https://github.com/hubmapconsortium/ingest-api/commit/82df881404e55e3367ad841dc796d997d34f5e9e), our workflow is NEVER merge `dev-integrate` into your feature branch.

I'm so sorry to do this again, I was being overly hasty. Reverting.

**Comment by yuanzhou** [comment]
@gesinaphillips might be a good idea to delete that commit from the history and force push to your branch. Reverting a commit creates a new commit too.

**Comment by gesinaphillips** [comment]
> @gesinaphillips might be a good idea to delete that commit from the history and force push to your branch. Reverting a commit creates a new commit too.

Ah. I thought that keeping the history might be preferred, so I went with the new commit @yuanzhou

**Comment by yuanzhou** [comment]
@gesinaphillips for some reason the revert commit doesn't look good to me. 

The old commit: https://github.com/hubmapconsortium/ingest-api/commit/82df881404e55e3367ad841dc796d997d34f5e9e had introduced several new changes being tested on DEV from other developers.

The revert commit https://github.com/hubmapconsortium/ingest-api/commit/8de3415f0ea0aa6108d5f51c25c4a809e3fbd53d only reverted a small part of the changes introduced by the above commit.

I'd suggest to delete the last two commits, one at a time with 
```
# git reset --hard HEAD~1
```
Then verify again to make sure you are at https://github.com/hubmapconsortium/ingest-api/pull/435/commits/e4cdb9819dac0268d4f0265ef256a3330e2164e1. 

Finally push to the feature branch 
```
# git push origin HEAD --force
```

**Comment by gesinaphillips** [comment]
@yuanzhou Okay that should do it! Thank you very much for the instructions.

**Review by gesinaphillips — APPROVED** [review]

**Review by yuanzhou — APPROVED** [review]
Will build on DEV using the IVT latest commit `f36a1ea90ee5e4ae79da6c3ef9082a67930e7c00` from branch `phillips/multi-assay`

**Pull request merged**
