### PR TITLE
Welling/soft assay types start

### PR DESCRIPTION
**Pull request by jswelling**
This PR provides the basics of a 'soft assay types' infrastructure, including the rule engine and the Flask blueprint that employs it.  3 endpoints are included: a GET endpoint which returns the output of a rule chain based on metadata pulled from entity-api based on a uuid, a POST endpoint which returns the result of the rule chain for metadata included as JSON in the request, and a PUT endpoint which causes the set of rules to be reloaded.  

A very simple CI test is provided.

### CODE REVIEW

**Comment by yuanzhou** [comment]
@jswelling I changed the base branch of this PR to `dev-integrate` to follow our workflow. Will you be able to test on DEV?

**Comment by jswelling** [comment]
@yuanzhou i don't know how to do a meaningful test on DEV without integration with other components, most importantly UBKG. We could set up an ad hot source for the rules set, like a json file somewhere, and configure DEV to pull rules from that source. The clients that will ultimately use the new service could at least begin development if we did so. Is that how you folks would like to proceed?
It's also probably desirable to configure different access restrictions for the 'reload' endpoint than for the other endpoints. Is that something you folks can do during deployment?

**Comment by yuanzhou** [comment]
@jswelling that sounds like a good plan. We have a DEV instance of UBKG ontology API too `https://ontology-api.dev.hubmapconsortium.org/`. 

TO-DO:
1. Add 3 new endpoints to "old gateway":

- `POST /assaytype` requires HuBMAP-Read group token
- `GET /assaytype/<ds_uuid>` requires HuBMAP-Read group token
- `PUT /reload` requires HuBMAP-Data-Admin group token

2. Using a json file is fine for what we do now, I may need to map it to the docker container too

3. Notify @AlanSimmons about use cases and samples (will need to produce output containing assay type string (to specify workflow), directory schema string, and vitessce hints for this interim implementation) so that he can start the modeling in UBKG

**Comment by yuanzhou** [comment]
FYI @jswelling @jpuerto-psc I just updated Joel's branch with some latest changes, also because a breaking dependency failed the CI. Will get the changed merged and redeployed on DEV once I have the new endpoints in place.

**Review by yuanzhou — APPROVED** [review]

**Pull request merged**
