### PR TITLE
Welling/cleanup and add provenance

### PR DESCRIPTION
**Pull request by jswelling**
This PR:
* removes files which have been moved to the new soft-assay-rules repo.  This includes the rule generator and tester, the captured copy of the old assay_types.yaml file, and the contents of the test examples directory.
* adds a field of provenance info to the info available to matching rules.  This serves some special case needs for legacy assay types needing vitessce-hints which cannot be computed without provenance.

### CODE REVIEW

**Comment by yuanzhou** [comment]
FYI @jswelling @j-uranic I'm off Wednesday, will take care of the PR on Thursday. Please feel free to append any additional updates to the branch. It also seems this branch is based on `jpuerto/assay_classifier_updates` which has a few recent tweaks deployed on DEV.

**Comment by j-uranic** [comment]
Hi @yuanzhou, I think I was tagged by mistake in your message instead of @jpuerto-psc .

**Review by jpuerto-psc — APPROVED** [review]

**Comment by jpuerto-psc** [comment]
@yuanzhou - these change are fine, I believe my branch updated some of the deleted files, but I was only doing so to copy over changes from the soft-assay repository. Since Joel has separate these two things now, we can just delete these files as Joel has done here.

**Comment by yuanzhou** [comment]
> Hi @yuanzhou, I think I was tagged by mistake in your message instead of @jpuerto-psc .

Oops, my bad. @j-uranic hope everything is well with you, it's been a while since we talked last time.

**Pull request merged**
